Restaurant.create({name: 'shalimar', address: 'graslin', phonenum: 33427616, category: 'indian'})
Restaurant.create({name: 'cigale', address: 'graslin', phonenum: 33427616, category: 'french'})
Restaurant.create({name: 'sushis shop', address: 'chateau des ducs', phonenum: 33427616, category: 'japaneese'})
Restaurant.create({name: 'subway', address: 'pommeray', phonenum: 33427616, category: 'fastfood'})
Restaurant.create({name: 'naantais', address: 'feydeau', phonenum: 33427616, category: 'indian'})
