Restaurant.create({name: 'shalimar', address: 'graslin', category: 'indian'})
Restaurant.create({name: 'cigale', address: 'graslin', category: 'french'})
Restaurant.create({name: 'sushis shop', address: 'chateau des ducs', category: 'japaneese'})
Restaurant.create({name: 'subway', address: 'pommeray', category: 'fastfood'})
Restaurant.create({name: 'naantais', address: 'feydeau', category: 'indian'})
