Restaurant.create({name: 'shalimar', address: 'graslin', phone_number: '33427616', category: 'indian'})
Restaurant.create({name: 'cigale', address: 'graslin', phone_number: '33427616', category: 'french'})
Restaurant.create({name: 'sushis shop', address: 'chateau des ducs', phone_number: '33427616', category: 'japaneese'})
Restaurant.create({name: 'subway', address: 'pommeray', phone_number: '33427616', category: 'fastfood'})
Restaurant.create({name: 'naantais', address: 'feydeau', phone_number: '33427616', category: 'indian'})
